### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by K9420** [ederekun/x_kernel_oneplus_msm8998#1]
![微信截图_20220310124731](https://user-images.githubusercontent.com/56768839/157591646-4918f6bd-0576-4e36-91f2-180ed805a3f0.png)

compile command: `make  NM=llvm-nm OBJCOPY=llvm-objcopy LD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CC=clang AR=llvm-ar OBJDUMP=llvm-objdump STRIP=llvm-strip O=out ARCH=arm64 SUBARCH=arm64`

**Comment by ederevx** [comment]
I have not encountered such issue, what branch have you compiled and have you made any changes?

**Comment by ederevx** [comment]
I suggest you contact me through telegram if this is to be discussed further. Thanks.
