### ISSUE TITLE
Excuse me: How to make 4.4 kernel support Android 12

### ISSUE THREAD

**Issue by Ten-Shine** [ederekun/x_kernel_oneplus_msm8998#2]
Forgive my interruption. I don't know how to contact you so I just submit an issue.

I have a problem need to ask you for advice. It is like the topic. Now the version of my device kernel is 4.4 and I cannot use it to build Android 12. Then I saw your changelog
```
 - Upstreamed 4.4.302 merged
- Latest CAF tag and wifi stack merged for msm8998
- Built with latest LLVM Clang 13 from Google toolchain prebuilts
- Android 12 support (BPF patches by LOS kernel)
- Schedtune input-assisted boosting timeout (Utilizes a custom timeout API)
- ...
```
And now I'm here. If my issue disturb you, I'm sorry and you can delete the issue.

**Comment by ederevx** [comment]
Android 12 support largely depends on the ROM you want to support. Initially, we needed BPF support patches for our kernel which Maitreya found and got from other devs and shared to the community; however, later on, LOS dev found a way to workaround the issue through some patches on the ROM side.

I'm not much familiar with the BPF stuff so I recommend you contacting them for further details. 

I have retained the BPF patches as to retain compatibility with earlier A12 builds which require the BPF patches as it was the first method to be discovered by ROM developers (it does not conflict with LOS workaround as far as I know).

That's all I know. Goodluck 👌

**Comment by ederevx** [comment]
In addition to this, the LOS kernel I base on is older than what is currently in their official repos as they have gotten rid of the patches quite sometime ago.

**Comment by Ten-Shine** [comment]
Thank you very much.
