### ISSUE TITLE
What compiler should I use?

### ISSUE THREAD

**Issue by rogxo** [ederekun/x_kernel_oneplus_msm8998#3]
Plz tell me compiler version.
I met a lot of errors and warnings.

**Comment by ederevx** [comment]
Use Clang 14 or 15, make sure to use LLVM alongside. GCC and probably any other compilers won't be able to compile the kernel.

**Comment by rogxo** [comment]
> Use Clang 14 or 15, make sure to use LLVM alongside. GCC and probably any other compilers won't be able to compile the kernel.

thx,solved
